package agentcli

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
)

// enrollmentStateSchema mirrors agent/enrollment's private state file so
// that a key generated by init is accepted by a later enroll without a
// second identity being created.
const enrollmentStateSchema = "antiflock.agent-enrollment/v1"

// InitOptions drives Initialize.
type InitOptions struct {
	ConfigPath string
	Config     Config
	// Force allows replacing an existing config file. It never replaces an
	// existing node key: a key is only generated when none exists.
	Force bool
}

// InitResult is the result payload of the init command. It never contains
// key material.
type InitResult struct {
	ConfigPath   string `json:"configPath"`
	ConfigDigest string `json:"configDigest"`
	StateDir     string `json:"stateDir"`
	QueueDir     string `json:"queueDir"`
	KeyPath      string `json:"keyPath"`
	KeyID        string `json:"keyId"`
	KeyCreated   bool   `json:"keyCreated"`
	ConfigWrote  bool   `json:"configWritten"`
}

// Initialize creates the directory layout, the node key, and the config
// file. Directories are 0700, files 0600. An existing key is reused and its
// id reported; an existing config is only replaced with Force.
func Initialize(options InitOptions) (InitResult, Reason, error) {
	config := options.Config
	if err := config.Validate(); err != nil {
		return InitResult{}, Reason{Code: "AF-INIT-CONFIG-INVALID", Message: err.Error()}, err
	}
	if !filepath.IsAbs(options.ConfigPath) || filepath.Clean(options.ConfigPath) != options.ConfigPath {
		err := errors.New("config path must be absolute and canonical")
		return InitResult{}, Reason{Code: "AF-INIT-CONFIG-PATH-INVALID", Message: err.Error()}, err
	}
	if _, err := os.Lstat(options.ConfigPath); err == nil && !options.Force {
		err := errors.New("config file already exists; use --force to replace it")
		return InitResult{}, Reason{Code: "AF-INIT-CONFIG-EXISTS", Message: err.Error()}, err
	} else if err != nil && !errors.Is(err, os.ErrNotExist) {
		err := errors.New("inspect config file")
		return InitResult{}, Reason{Code: "AF-INIT-CONFIG-PATH-INVALID", Message: err.Error()}, err
	}
	if err := os.MkdirAll(filepath.Dir(options.ConfigPath), 0o755); err != nil {
		err = errors.New("create config directory")
		return InitResult{}, Reason{Code: "AF-INIT-DIRECTORY", Message: err.Error()}, err
	}
	for _, directory := range []string{config.StateDir, config.QueueDir} {
		if err := ensurePrivateDirectory(directory); err != nil {
			return InitResult{}, Reason{Code: "AF-INIT-DIRECTORY", Message: err.Error()}, err
		}
	}
	result := InitResult{ConfigPath: options.ConfigPath, StateDir: config.StateDir, QueueDir: config.QueueDir, KeyPath: config.KeyPath()}
	keyID, created, err := ensureNodeKey(config)
	if err != nil {
		return InitResult{}, Reason{Code: "AF-INIT-KEY", Message: err.Error()}, err
	}
	result.KeyID, result.KeyCreated = keyID, created
	content, err := config.Encode()
	if err != nil {
		return InitResult{}, Reason{Code: "AF-INIT-CONFIG-INVALID", Message: err.Error()}, err
	}
	if err := writeConfigAtomic(options.ConfigPath, content); err != nil {
		return InitResult{}, Reason{Code: "AF-INIT-CONFIG-WRITE", Message: err.Error()}, err
	}
	result.ConfigDigest, result.ConfigWrote = Digest(content), true
	return result, Reason{Code: "AF-INIT-OK", Message: "agent layout initialized"}, nil
}

// KeyID derives the public identifier of a seed file without exposing it.
func KeyID(seedPath string) (string, error) {
	info, err := os.Lstat(seedPath)
	if err != nil || !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 || info.Mode().Perm() != PrivateFileMode || info.Size() != ed25519.SeedSize {
		return "", errors.New("node key must be a private regular Ed25519 seed file")
	}
	seed, err := os.ReadFile(seedPath)
	if err != nil || len(seed) != ed25519.SeedSize {
		return "", errors.New("read node key")
	}
	return publicKeyID(ed25519.NewKeyFromSeed(seed).Public().(ed25519.PublicKey)), nil
}

func publicKeyID(publicKey ed25519.PublicKey) string {
	sum := sha256.Sum256(publicKey)
	return "ed25519:" + hex.EncodeToString(sum[:8])
}

func ensureNodeKey(config Config) (string, bool, error) {
	seedPath := config.KeyPath()
	if _, err := os.Lstat(seedPath); err == nil {
		keyID, err := KeyID(seedPath)
		return keyID, false, err
	} else if !errors.Is(err, os.ErrNotExist) {
		return "", false, errors.New("inspect node key")
	}
	if _, err := os.Lstat(config.EnrollmentStatePath()); err == nil {
		return "", false, errors.New("enrollment state exists without a node key; remove it or restore the key")
	}
	publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return "", false, errors.New("generate node key")
	}
	requestID := make([]byte, 12)
	if _, err := rand.Read(requestID); err != nil {
		return "", false, errors.New("generate enrollment request id")
	}
	state, err := json.Marshal(map[string]string{"schemaVersion": enrollmentStateSchema, "nodeId": config.NodeID, "requestId": "enroll-" + hex.EncodeToString(requestID)})
	if err != nil {
		return "", false, errors.New("encode enrollment state")
	}
	if err := writePrivateNew(seedPath, privateKey.Seed()); err != nil {
		return "", false, err
	}
	if err := writePrivateNew(config.EnrollmentStatePath(), state); err != nil {
		_ = os.Remove(seedPath)
		return "", false, err
	}
	return publicKeyID(publicKey), true, nil
}

func ensurePrivateDirectory(directory string) error {
	if err := os.MkdirAll(directory, PrivateDirectoryMode); err != nil {
		return errors.New("create private directory")
	}
	if !RealDirectory(directory) {
		return errors.New("private directory must be a real directory, not a symlink")
	}
	if err := os.Chmod(directory, PrivateDirectoryMode); err != nil {
		return errors.New("protect private directory")
	}
	return nil
}

func writePrivateNew(path string, content []byte) error {
	return writeNew(path, content, PrivateFileMode)
}

// ConfigFileMode: the config carries no secret, and the service user must
// read it while root owns it.
const ConfigFileMode = 0o644

func writeNew(path string, content []byte, mode os.FileMode) error {
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, mode)
	if err != nil {
		return errors.New("create private file")
	}
	if _, err := file.Write(content); err != nil {
		_ = file.Close()
		return errors.New("write private file")
	}
	if err := file.Sync(); err != nil {
		_ = file.Close()
		return errors.New("sync private file")
	}
	return file.Close()
}

func writeConfigAtomic(path string, content []byte) error {
	staging := path + ".tmp"
	_ = os.Remove(staging)
	if err := writeNew(staging, content, ConfigFileMode); err != nil {
		return err
	}
	if err := os.Rename(staging, path); err != nil {
		_ = os.Remove(staging)
		return errors.New("install file atomically")
	}
	return nil
}
