import type { DashboardData, ProtectionState } from "../api/contracts";

const T = {
  joined: "2026-07-21T13:42:08.000Z",
  verifying: "2026-07-21T13:42:09.000Z",
  exposed: "2026-07-21T13:42:11.000Z",
  held: "2026-07-21T13:42:14.000Z",
  now: "2026-07-21T13:42:18.000Z",
};

export function createDemoData(state: ProtectionState = "EXPOSED"): DashboardData {
  const protectedState = state === "PROTECTED";
  const verifying = state === "VERIFYING";
  const exposed = !protectedState && !verifying;
  const meshState = protectedState ? "trusted" : verifying ? "unknown" : "blocked";
  const findingStatus = protectedState ? "resolved" : "open";

  return {
    overview: {
      operatorName: "Local operator",
      deploymentName: "Aether home domain",
      simulation: true,
      environment: {
        name: protectedState ? "Home network" : "Rook & Pine Coffee",
        type: protectedState ? "home" : "public",
        trust: protectedState ? "trusted" : "untrusted",
        security: protectedState ? "WPA3" : "WPA2 \u00b7 shared network",
        known: protectedState,
        gateway: protectedState ? "home-router" : "10.24.0.1 \u00b7 first seen today",
        changedAt: protectedState ? "2026-07-21T12:10:00.000Z" : T.joined,
      },
      protectedDevices: protectedState ? 4 : 3,
      totalDevices: 4,
      openFindings: protectedState ? 1 : 2,
      heldActions: exposed ? 1 : 0,
      currentExit: protectedState ? "home-gateway \u00b7 nyc" : "No approved exit verified",
      exitVerified: protectedState,
      dnsState: protectedState ? "verified" : verifying ? "unknown" : "unverified",
      dnsResolver: protectedState ? "100.100.100.100 \u00b7 mesh DNS" : "Resolver identity unavailable",
      scramblerState: protectedState ? "Active \u00b7 state 8E21" : "Paused \u00b7 protection prerequisite failed",
    },
    posture: {
      state,
      reasonCode: protectedState ? "AF-OK-000" : verifying ? "AF-VERIFY-001" : "AF-PATH-001",
      summary: protectedState
        ? "Required controls are verified for the active path."
        : verifying
          ? "AntiFlock is rechecking the mesh, DNS, and external exit identity."
          : "The approved secure route is unavailable on an untrusted network.",
      evaluatedAt: protectedState ? T.now : verifying ? T.verifying : T.exposed,
      confidence: protectedState ? 0.99 : verifying ? 0.61 : 0.98,
      evidenceClass: protectedState ? "Verified" : verifying ? "Unknown" : "Detected",
      checks: [
        {
          id: "mesh",
          label: "Private mesh",
          state: protectedState ? "pass" : verifying ? "unknown" : "fail",
          observed: protectedState ? "Connected via direct peer path" : verifying ? "Handshake probe pending" : "Interface present; approved peer unreachable",
          expected: "Connected to an approved peer",
          evidenceClass: protectedState ? "Verified" : verifying ? "Unknown" : "Detected",
          checkedAt: protectedState ? T.now : T.exposed,
        },
        {
          id: "exit",
          label: "Approved exit",
          state: protectedState ? "pass" : verifying ? "unknown" : "fail",
          observed: protectedState ? "home-gateway \u00b7 nyc" : verifying ? "Probe in progress" : "No matching external egress identity",
          expected: "home-gateway \u00b7 nyc",
          evidenceClass: protectedState ? "Verified" : verifying ? "Unknown" : "Detected",
          checkedAt: protectedState ? T.now : T.exposed,
        },
        {
          id: "dns",
          label: "DNS path",
          state: protectedState ? "pass" : "unknown",
          observed: protectedState ? "Mesh resolver verified" : "Resolver identity cannot be verified while route is down",
          expected: "100.100.100.100 \u00b7 mesh DNS",
          evidenceClass: protectedState ? "Verified" : "Unknown",
          checkedAt: protectedState ? T.now : T.exposed,
        },
        {
          id: "recovery",
          label: "Recovery path",
          state: "pass",
          observed: "Core recovery endpoint reachable",
          expected: "Recovery traffic remains permitted",
          evidenceClass: "Detected",
          checkedAt: T.now,
        },
      ],
    },
    nodes: [
      {
        id: "pixel-9",
        name: "Operator phone",
        kind: "phone",
        platform: "Android 16",
        state: exposed ? "blocked" : "online",
        protection: state,
        lastSeen: T.now,
        network: protectedState ? "Home network" : "Rook & Pine Coffee",
        meshAddress: "100.82.14.7",
        agentVersion: "0.1.0-alpha",
        capabilities: ["wifi identity", "DNS verify", "exit verify", "fail-closed guard"],
        tags: ["operator", "mobile", "shielded"],
      },
      {
        id: "atlas-laptop",
        name: "Atlas laptop",
        kind: "laptop",
        platform: "Linux 6.12",
        state: "online",
        protection: "PROTECTED",
        lastSeen: T.now,
        network: "Aether mesh",
        meshAddress: "100.82.14.12",
        agentVersion: "0.1.0-alpha",
        capabilities: ["flows", "routes", "DNS", "nftables", "process attribution \u00b7 partial"],
        tags: ["operator", "development"],
      },
      {
        id: "home-gateway",
        name: "Home gateway",
        kind: "gateway",
        platform: "Debian 13",
        state: protectedState ? "online" : "stale",
        protection: protectedState ? "PROTECTED" : "UNKNOWN",
        lastSeen: protectedState ? T.now : "2026-07-21T13:41:52.000Z",
        network: "Home uplink",
        meshAddress: "100.82.14.1",
        agentVersion: "0.1.0-alpha",
        capabilities: ["trusted exit", "DNS", "nftables", "rollback"],
        tags: ["gateway", "approved-exit"],
      },
      {
        id: "aether-code",
        name: "Aether Code",
        kind: "agent",
        platform: "Secure Action SDK",
        state: "online",
        protection: state,
        lastSeen: T.now,
        network: "Operator phone",
        meshAddress: "local app service",
        agentVersion: "sdk 0.1.0",
        capabilities: ["secure actions", "destination policy", "hold and retry"],
        tags: ["agent", "integrated"],
      },
    ],
    paths: [
      {
        id: "path-aether-github",
        application: "Aether Code",
        sourceNodeId: "pixel-9",
        destination: "api.github.com",
        state: protectedState ? "active" : verifying ? "unknown" : "held",
        encrypted: protectedState ? true : null,
        policy: "Shielded \u00b7 fail closed",
        updatedAt: protectedState ? T.now : T.held,
        segments: [
          { id: "app", label: "Aether Code", kind: "application", state: "trusted", detail: "Integrated secure action", evidenceClass: "Detected" },
          { id: "phone", label: "Operator phone", kind: "device", state: "trusted", detail: "Android Guard active", evidenceClass: "Detected" },
          { id: "policy", label: "Shielded policy", kind: "policy", state: "trusted", detail: "Protected path required", evidenceClass: "Verified" },
          { id: "mesh", label: "Private mesh", kind: "mesh", state: meshState, detail: protectedState ? "Direct peer path" : "Approved peer unreachable", evidenceClass: protectedState ? "Verified" : verifying ? "Unknown" : "Detected" },
          { id: "exit", label: "Home gateway", kind: "exit", state: meshState, detail: protectedState ? "External identity verified" : "Exit identity unavailable", evidenceClass: protectedState ? "Verified" : "Unknown" },
          { id: "dns", label: "Mesh DNS", kind: "dns", state: protectedState ? "trusted" : "unknown", detail: protectedState ? "Resolver verified" : "Visibility unavailable", evidenceClass: protectedState ? "Verified" : "Unknown" },
          { id: "dest", label: "api.github.com", kind: "destination", state: protectedState ? "trusted" : "blocked", detail: protectedState ? "Destination allowed" : "Request held locally", evidenceClass: "Detected" },
        ],
      },
    ],
    topology: [
      { id: "e1", source: "operator", target: "pixel-9", label: "controls", state: "trusted", evidenceClass: "Verified" },
      { id: "e2", source: "operator", target: "atlas-laptop", label: "controls", state: "trusted", evidenceClass: "Verified" },
      { id: "e3", source: "pixel-9", target: "home-gateway", label: "approved mesh path", state: meshState, evidenceClass: protectedState ? "Verified" : "Detected" },
      { id: "e4", source: "home-gateway", target: "api.github.com", label: "approved egress", state: protectedState ? "trusted" : "unknown", evidenceClass: protectedState ? "Verified" : "Unknown" },
    ],
    events: [
      {
        id: "evt-hold",
        kind: "action.held",
        title: "Sensitive action held",
        summary: "Aether Code request to api.github.com is held locally because the approved route is unavailable.",
        observedAt: T.held,
        receivedAt: T.held,
        evidenceClass: "Detected",
        confidence: 1,
        severity: "high",
        nodeId: "pixel-9",
        reasonCode: "AF-PATH-001",
      },
      {
        id: "evt-finding",
        kind: "finding.opened",
        title: "Approved secure route unavailable",
        summary: "AF-PATH-001 opened after two route probes failed on an untrusted network.",
        observedAt: T.exposed,
        receivedAt: T.exposed,
        evidenceClass: "Detected",
        confidence: 0.98,
        severity: "critical",
        nodeId: "pixel-9",
        reasonCode: "AF-PATH-001",
      },
      {
        id: "evt-wifi",
        kind: "network.wifi_changed",
        title: "Joined an untrusted network",
        summary: "Operator phone joined Rook & Pine Coffee. This network was not previously trusted.",
        observedAt: T.joined,
        receivedAt: T.joined,
        evidenceClass: "Detected",
        confidence: 1,
        severity: "medium",
        nodeId: "pixel-9",
      },
      {
        id: "evt-field",
        kind: "field.report_imported",
        title: "Regional intelligence pack refreshed",
        summary: "Two nearby infrastructure reports matched locally. Exact device location was not uploaded.",
        observedAt: "2026-07-21T13:40:00.000Z",
        receivedAt: "2026-07-21T13:40:00.000Z",
        evidenceClass: "Reported",
        confidence: 0.84,
        severity: "info",
        nodeId: "pixel-9",
      },
    ],
    findings: [
      {
        id: "finding-path",
        ruleId: "AF-PATH-001",
        title: "Approved secure route unavailable",
        condition: "The phone is on an untrusted network and cannot verify the required trusted exit.",
        consequence: "Protected traffic is paused. Recovery and approved connectivity probes remain allowed.",
        recommendation: protectedState ? "No action is required. Continue monitoring." : "Restore the private mesh and verify DNS plus external egress identity before releasing held actions.",
        falsePositiveNote: "A failed route can be caused by ordinary connectivity loss. It does not by itself indicate interception.",
        status: findingStatus,
        severity: "critical",
        classification: "Detected",
        confidence: 0.98,
        firstSeen: T.exposed,
        lastSeen: protectedState ? T.now : T.exposed,
        evidence: [
          { id: "ev-path-1", label: "Approved exit probe", value: protectedState ? "Matched home-gateway" : "No matching egress identity", source: "Android Guard route verifier", observedAt: protectedState ? T.now : T.exposed, lastVerifiedAt: protectedState ? T.now : T.exposed, evidenceClass: "Detected", confidence: 0.99 },
          { id: "ev-path-2", label: "Current network trust", value: protectedState ? "trusted \u00b7 home" : "untrusted \u00b7 first seen today", source: "Android network monitor", observedAt: protectedState ? T.now : T.joined, lastVerifiedAt: protectedState ? T.now : T.joined, evidenceClass: "Detected", confidence: 1 },
          { id: "ev-path-3", label: "Interception status", value: "Active interception is not confirmed", source: "AntiFlock evidence policy", observedAt: T.exposed, lastVerifiedAt: T.exposed, evidenceClass: "Unknown", confidence: 0 },
        ],
      },
      {
        id: "finding-service",
        ruleId: "AF-SVC-001",
        title: "New listening service observed",
        condition: "Atlas laptop began listening on TCP 5173 after the previous inventory snapshot.",
        consequence: "A development service may be reachable from the local interface.",
        recommendation: "Confirm the service belongs to the local development environment or restrict its bind address.",
        falsePositiveNote: "Development servers commonly open temporary local ports. Process attribution is partial on this node.",
        status: "open",
        severity: "low",
        classification: "Detected",
        confidence: 0.86,
        firstSeen: "2026-07-21T12:58:00.000Z",
        lastSeen: "2026-07-21T13:41:00.000Z",
        evidence: [
          { id: "ev-svc-1", label: "Listening socket", value: "0.0.0.0:5173 \u00b7 TCP", source: "Linux socket collector", observedAt: "2026-07-21T12:58:00.000Z", lastVerifiedAt: "2026-07-21T13:41:00.000Z", evidenceClass: "Detected", confidence: 1 },
          { id: "ev-svc-2", label: "Process attribution", value: "node \u00b7 best-effort match", source: "Linux process correlator", observedAt: "2026-07-21T12:58:00.000Z", lastVerifiedAt: "2026-07-21T13:41:00.000Z", evidenceClass: "Inferred", confidence: 0.72 },
        ],
      },
    ],
    actions: [
      {
        id: "act-aether-send",
        operationId: "demo-operation-aether-send",
        application: "Aether Code",
        nodeId: "node-phone",
        actionType: "repository request",
        destination: "api.github.com",
        destinations: ["api.github.com"],
        dataClass: "repository metadata \u00b7 sensitive",
        decision: protectedState ? "ALLOW" : exposed ? "HOLD" : "REQUIRE_CONSENT",
        reasonCodes: protectedState ? ["AF-OK-000"] : ["AF-PATH-001", "AF-NET-UNTRUSTED"],
        createdAt: T.held,
        expiresAt: "2026-07-21T13:47:14.000Z",
        oneTimeAuthorization: {
          enabled: !protectedState,
          maximumExpiresAt: "2026-07-21T13:47:14.000Z",
          consentReasonCode: "USER_EXPLICIT",
        },
      },
    ],
    policies: [
      {
        id: "policy-shielded",
        name: "Shielded",
        mode: "Shield",
        status: "active",
        revision: 12,
        updatedAt: "2026-07-20T22:14:00.000Z",
        targetCount: 3,
        rules: [
          { id: "r-mesh", label: "Private mesh", value: "Required", enforcement: "shield" },
          { id: "r-egress", label: "Internet egress", value: "Trusted exit \u00b7 fail closed", enforcement: "shield" },
          { id: "r-dns", label: "DNS", value: "Approved resolver only", enforcement: "guard" },
          { id: "r-public", label: "Public Wi-Fi bypass", value: "One action \u00b7 5 minutes", enforcement: "shield" },
          { id: "r-payload", label: "Packet payload capture", value: "Disabled", enforcement: "observe" },
        ],
      },
      {
        id: "policy-observe",
        name: "Observer",
        mode: "Observe",
        status: "draft",
        revision: 4,
        updatedAt: "2026-07-18T17:00:00.000Z",
        targetCount: 1,
        rules: [
          { id: "r-observe", label: "Network changes", value: "Record and explain", enforcement: "observe" },
        ],
      },
    ],
    fieldReports: [
      {
        id: "field-alpr-1",
        category: "Fixed ALPR installation",
        label: "Intersection camera mast",
        distance: "approximately 230\u2013310 m",
        locationPrecision: "street segment \u00b7 \u00b180 m",
        direction: "north-east of current area",
        classification: "Reported",
        confidence: 0.91,
        status: "documented",
        source: "Municipal equipment record + community photograph",
        observedAt: "2026-05-19T15:00:00.000Z",
        lastVerifiedAt: "2026-07-03T18:00:00.000Z",
        expiresAt: "2026-10-03T18:00:00.000Z",
        coordinates: { x: 72, y: 28 },
      },
      {
        id: "field-alpr-2",
        category: "Fixed ALPR installation",
        label: "Parking entrance camera pair",
        distance: "approximately 420\u2013560 m",
        locationPrecision: "site boundary \u00b7 \u00b1120 m",
        direction: "west of current area",
        classification: "Reported",
        confidence: 0.76,
        status: "corroborated",
        source: "Two independent community reports",
        observedAt: "2026-06-08T12:00:00.000Z",
        lastVerifiedAt: "2026-06-29T16:00:00.000Z",
        expiresAt: "2026-09-29T16:00:00.000Z",
        coordinates: { x: 23, y: 58 },
      },
      {
        id: "field-camera-registry",
        category: "Public camera registry area",
        label: "Downtown registry coverage",
        distance: "current area intersects registry boundary",
        locationPrecision: "district polygon",
        direction: "current area",
        classification: "Reported",
        confidence: 0.68,
        status: "documented",
        source: "Published municipal registry boundary",
        observedAt: "2026-01-12T12:00:00.000Z",
        lastVerifiedAt: "2026-07-01T12:00:00.000Z",
        expiresAt: "2027-01-01T12:00:00.000Z",
        coordinates: { x: 53, y: 47 },
      },
    ],
    footprintAssets: [
      { id: "asset-email", type: "Email", label: "operator@aether.example", verification: "verified", exposure: "limited", lastCheckedAt: "2026-07-20T02:00:00.000Z", findings: 1 },
      { id: "asset-domain", type: "Domain", label: "aether-lab.example", verification: "verified", exposure: "public", lastCheckedAt: "2026-07-21T05:00:00.000Z", findings: 0 },
      { id: "asset-repo", type: "Code repository", label: "Aether private workspace", verification: "verified", exposure: "private", lastCheckedAt: "2026-07-21T12:00:00.000Z", findings: 0 },
      { id: "asset-cert", type: "Certificate", label: "*.aether-lab.example", verification: "verified", exposure: "public", lastCheckedAt: "2026-07-21T05:00:00.000Z", findings: 0 },
      { id: "asset-service", type: "Hosted service", label: "gateway.aether-lab.example", verification: "pending", exposure: "unknown", lastCheckedAt: "2026-07-20T05:00:00.000Z", findings: 0 },
    ],
    footprintRelationships: [
      { id: "fr1", source: "asset-email", target: "asset-domain", label: "administrative identity", classification: "Verified" },
      { id: "fr2", source: "asset-domain", target: "asset-cert", label: "certificate covers", classification: "Detected" },
      { id: "fr3", source: "asset-domain", target: "asset-service", label: "resolves to service", classification: "Detected" },
      { id: "fr4", source: "asset-repo", target: "asset-domain", label: "declared deployment", classification: "Verified" },
    ],
    scrambler: {
      state: protectedState ? "ACTIVE" : "IDLE",
      profile: "Balanced",
      stateId: protectedState ? "8E21" : "8E21 \u00b7 retained",
      currentExit: protectedState ? "home-gateway \u00b7 nyc" : "No verified exit",
      proposedExit: "home-gateway-backup \u00b7 iad",
      lastTransitionAt: "2026-07-21T12:12:00.000Z",
      simulationOnly: true,
      risk: "low",
      checks: [
        { id: "sc-core", label: "Core reachable", state: "pass" },
        { id: "sc-peers", label: "Mesh peers reachable", state: protectedState ? "pass" : "fail" },
        { id: "sc-dns", label: "DNS working through approved path", state: protectedState ? "pass" : "unknown" },
        { id: "sc-leak", label: "No direct-route leak", state: protectedState ? "pass" : "pending" },
        { id: "sc-exit", label: "External exit identity correct", state: protectedState ? "pass" : "unknown" },
        { id: "sc-rollback", label: "Rollback state retained", state: "pass" },
      ],
    },
  };
}

export const DEMO_TIMESTAMPS = T;
